# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=32)),
                ('head', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=1048576)),
                ('md', models.CharField(default='A', max_length=1048576)),
            ],
        ),
    ]
